name: Antman
version: 2.0.0
main: KoalaBoy\Antman\Antman
api: [3.0.0-ALPHA5, 3.0.1, 3.0.0-ALPHA4]
author: KoalaBoy

commands:
  antman:
    aliases: [ant]
    description: Antman command.
    
permission:
  antman: 
    default: op
    description: Allow player to use antman command.
